import React from "react";
import { useEffect, useState } from "react";
import { ArrowLeftRight, RotateCcw, Plus, X } from "lucide-react";
import api from "../services/api";

export default function Circulation(){
 const [loans,setLoans]=useState([]),[books,setBooks]=useState([]),[members,setMembers]=useState([]),[modal,setModal]=useState(false),[form,setForm]=useState({bookId:"",memberId:"",dueDate:""}),[error,setError]=useState("");
 const load=()=>api.get("/loans").then(r=>setLoans(r.data)).catch(e=>setError(e.response?.data?.message||"Unable to load loans"));
 useEffect(()=>{load();api.get("/books").then(r=>setBooks(r.data));api.get("/users").then(r=>setMembers(r.data.filter(x=>x.role==="member")))},[]);
 async function issue(e){e.preventDefault();try{await api.post("/loans/issue",form);setModal(false);load()}catch(e){setError(e.response?.data?.message||"Could not issue book")}}
 async function ret(id){try{const r=await api.post(`/loans/${id}/return`);alert(`Book returned. Fine: ₹${r.data.fine}`);load()}catch(e){setError(e.response?.data?.message||"Return failed")}}
 return <><div className="page-head"><div><span className="eyebrow">CIRCULATION</span><h1>Issue & return</h1><p>Track active loans, due dates and overdue fines.</p></div><button className="primary-btn" onClick={()=>setModal(true)}><Plus size={18}/> Issue a book</button></div>{error&&<div className="alert error">{error}</div>}<div className="panel table-wrap"><table><thead><tr><th>Book</th><th>Member</th><th>Issue date</th><th>Due date</th><th>Status</th><th>Fine</th><th></th></tr></thead><tbody>{loans.map(l=><tr key={l._id}><td><strong>{l.book?.title}</strong><br/><small>{l.book?.author}</small></td><td>{l.member?.name}</td><td>{new Date(l.issueDate).toLocaleDateString()}</td><td>{new Date(l.dueDate).toLocaleDateString()}</td><td><span className={`status ${l.status==="overdue"?"unavailable":"available"}`}>{l.status}</span></td><td>₹{l.fine||0}</td><td>{!l.returnDate&&<button className="secondary-btn" onClick={()=>ret(l._id)}><RotateCcw size={15}/> Return</button>}</td></tr>)}</tbody></table>{loans.length===0&&<div className="empty-state"><ArrowLeftRight/><h3>No loans yet</h3></div>}</div>{modal&&<div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><h2>Issue a book</h2><p>Create a new loan with a due date.</p></div><button className="icon-btn" onClick={()=>setModal(false)}><X/></button></div><form onSubmit={issue}><label>Book<select required value={form.bookId} onChange={e=>setForm({...form,bookId:e.target.value})}><option value="">Select available book</option>{books.filter(b=>b.availableCopies>0).map(b=><option key={b._id} value={b._id}>{b.title} — {b.availableCopies} available</option>)}</select></label><label>Member<select required value={form.memberId} onChange={e=>setForm({...form,memberId:e.target.value})}><option value="">Select member</option>{members.map(m=><option key={m._id} value={m._id}>{m.name} — {m.email}</option>)}</select></label><label>Due date<input required type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></label><div className="modal-actions"><button type="button" className="secondary-btn" onClick={()=>setModal(false)}>Cancel</button><button className="primary-btn">Issue book</button></div></form></div></div>}</>;
}
