import React from "react";
import { useEffect, useState } from "react";
import { Users, UserPlus, Search, X } from "lucide-react";
import api from "../services/api";

export default function Members(){
 const [users,setUsers]=useState([]),[q,setQ]=useState(""),[modal,setModal]=useState(false),[form,setForm]=useState({name:"",email:"",password:"",role:"member",phone:""}),[error,setError]=useState("");
 const load=()=>api.get("/users").then(r=>setUsers(r.data)).catch(e=>setError(e.response?.data?.message||"Unable to load members"));
 useEffect(()=>{load()},[]);
 const filtered=users.filter(u=>(u.name+" "+u.email).toLowerCase().includes(q.toLowerCase()));
 async function save(e){e.preventDefault();try{await api.post("/users",form);setModal(false);setForm({name:"",email:"",password:"",role:"member",phone:""});load()}catch(e){setError(e.response?.data?.message||"Could not create member")}}
 return <><div className="page-head"><div><span className="eyebrow">PEOPLE</span><h1>Members</h1><p>Manage library accounts and access status.</p></div><button className="primary-btn" onClick={()=>setModal(true)}><UserPlus size={18}/> Add member</button></div>{error&&<div className="alert error">{error}</div>}<div className="toolbar"><div className="search-box"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search members..."/></div></div><div className="panel table-wrap"><table><thead><tr><th>Member</th><th>Contact</th><th>Role</th><th>Status</th><th>Joined</th></tr></thead><tbody>{filtered.map(u=><tr key={u._id}><td><div className="table-user"><div className="avatar">{u.name[0]}</div><strong>{u.name}</strong></div></td><td>{u.email}<br/><small>{u.phone||"No phone"}</small></td><td><span className="role-pill">{u.role}</span></td><td><span className={`status ${u.status==="active"?"available":"unavailable"}`}>{u.status}</span></td><td>{new Date(u.createdAt).toLocaleDateString()}</td></tr>)}</tbody></table></div>{modal&&<div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><h2>Add member</h2><p>Create a library account manually.</p></div><button className="icon-btn" onClick={()=>setModal(false)}><X/></button></div><form className="form-grid" onSubmit={save}><label>Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Email<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Password<input required minLength="6" type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><label>Role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="member">Member</option><option value="librarian">Librarian</option><option value="admin">Admin</option></select></label><label>Phone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><div className="modal-actions span-2"><button type="button" className="secondary-btn" onClick={()=>setModal(false)}>Cancel</button><button className="primary-btn">Create account</button></div></form></div></div>}</>;
}
